CREATE DATABASE SPMEDGROUP;

USE SPMEDGROUP;

CREATE TABLE TIPOS_USUARIOS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (100) NOT NULL UNIQUE
);

CREATE TABLE USUARIOS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL
	,EMAIL VARCHAR (250) NOT NULL UNIQUE
	,SENHA VARCHAR (250) NOT NULL
	,ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPOS_USUARIOS (ID)
);

CREATE TABLE ESPECIALIDADES (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE CLINICA (
	ID INT IDENTITY PRIMARY KEY
	,NOME_FANTASIA VARCHAR (255) NOT NULL
	,HORARIO_FUNCIONAMENTO VARCHAR (255) NOT NULL
	,CNPJ CHAR (14) NOT NULL UNIQUE
	,RAZAO_SOCIAL VARCHAR (255) NOT NULL 
	,ENDERECO VARCHAR (255) NOT NULL 
);

CREATE TABLE MEDICOS (
	ID INT IDENTITY PRIMARY KEY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS (ID)
	,CRM VARCHAR (50) NOT NULL UNIQUE
	,ID_ESPECIALIDADE INT FOREIGN KEY REFERENCES ESPECIALIDADES (ID)
	,ID_CLINICA INT FOREIGN KEY REFERENCES CLINICA (ID)
);

CREATE TABLE PRONTUARIOS (
	ID INT IDENTITY PRIMARY KEY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS (ID)
	,RG CHAR (9) NOT NULL UNIQUE
	,CPF CHAR (11) NOT NULL UNIQUE
	,DATA_NASCIMENTO DATE NOT NULL
	,TELEFONE VARCHAR(50)
	,ENDERECO VARCHAR (255) NOT NULL
);

CREATE TABLE SITUACOES (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (100) NOT NULL UNIQUE
);

CREATE TABLE CONSULTA (
	ID INT IDENTITY PRIMARY KEY
	,ID_PRONTUARIO INT FOREIGN KEY REFERENCES PRONTUARIOS (ID)
	,ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS (ID)
	,DATA_HORA_CONSULTA DATETIME NOT NULL
	,ID_SITUACAO INT FOREIGN KEY REFERENCES SITUACOES (ID)
	,DESCRICAO VARCHAR (255)
);

ALTER TABLE CONSULTA 
	ADD CONSTRAINT HORA_MEDICO UNIQUE (ID_MEDICO, DATA_HORA_CONSULTA)
